Post/urls.py
from django.urls import path
from . import views
# from user import views as u_views
# from .views import PostListView, PostDetailView, PostUpdateView, PostDeleteView, Search
# , CommentCreateView
# from .views import commentFunc
from .views import PostListView
urlpatterns = [
    # path('', PostDetailView.as_view()),
    # path('', PostListView),
    # path('', PostListView, name='blog-home'),
    # path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<type>/new/', views.postcreate, name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('post/<int:pk>/comment/new/', commentFunc, name='post-comment'),
    # path('like/$', views.likepost, name = 'like-post'),
    # path('<tag>/explore/', views.ExploreTagView, name = 'explore-tag'),
    # path('poll/create/',views.pollnew,name='poll_create'),
    # path('poll/add/<int:pk>/<int:pollid>/',views.addpoll,name='addpoll'),
    # path('search/', Search, name='search'),
]

api/urls.py
from django.urls import path
# from .views import RoomView,CreateRoomView,GetRoom,JoinRoom,UserInRoom,LeaveRoom,UpdateRoom
from Profile.views import checkUsernameExistence, checkEmailExistence, ProfileDetailView
from .views import CommentListView,getMyInfo
from Post.views import PostListView, post_like, post_dislike, comment_like, comment_dislike, PostDetailView, \
    CommentDetailView

urlpatterns = [
    path('post/like', post_like),
    path('post/dislike', post_dislike),
    path('post/<post_id>', PostDetailView.as_view()),
    path('post', PostDetailView.as_view()),
    path('posts', PostListView.as_view()),
    # path('post/create', PostCreateView.as_view()),
    path('profile/<username>', ProfileDetailView.as_view()),
    path('currentInfo', getMyInfo),
    path('commentSection/<post_id>', CommentListView.as_view()),
    path('checkEmailExistence', checkEmailExistence),
    path('checkUserNameExistence', checkUsernameExistence),
    # path('posts', PostListView.as_view()),
    path('comment/like', comment_like),
    path('comment/dislike', comment_dislike),
    path('comment/dislike', comment_dislike),
    path('comment', CommentDetailView.as_view()),

]
# path('home', RoomView.as_view()),
# path('create-room', CreateRoomView.as_view()),
# path('get-room', GetRoom.as_view()),
# path('join-room', JoinRoom.as_view()),
# path('user-in-room', UserInRoom.as_view()),
# path('leave-room', LeaveRoom.as_view()),
# path('update-room', UpdateRoom.as_view()),

kilogram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from kilogram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('api/auth/', include("Profile.urls")),
    path('', include("frontend.urls")),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# from Tag.models import Tag
# from Group.models import Channel
from mptt.models import TreeForeignKey,MPTTModel
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	views = models.ManyToManyField(User, related_name='post_views', blank = True)
	likers = models.ManyToManyField(User, related_name = 'post_likers', blank = True)
	image = models.ImageField(upload_to='images/',default="images/temp.png")
	# tags = models.ManyToManyField(Tag, related_name = 'tags', blank = True)
	# type = models.IntegerField(default=0)
	# def get_absolute_url(self):
	# 	return reverse('post-detail', kwargs = {'pk':self.pk})
	def __str__(self):
		return self.title

# class GroupPost(Post):
# 	parentchannel = models.ForeignKey(Channel, related_name = "parent_channel", on_delete=models.CASCADE)

class Comment(MPTTModel):
	content = models.TextField()
	date_posted = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,blank=True, related_name='children')
	likers = models.ManyToManyField(User, related_name='comment_likers', blank=True)
	# class MPTTMeta:
		# level_attr = 'mptt_level'
		# order_insertion_by = ['order']

#
# 	def get_absolute_url(self):
# 		return reverse('post-detail', kwargs = {'pk':self.post.pk})

# class Poll(models.Model):
# 	title=models.CharField(max_length=100)
# 	# tags = models.ManyToManyField(Tag, related_name = 'tags', blank = True)
#
# 	def __str__(self):
# 		return self.title

# class PollChoice(models.Model):
# 	poll = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='poll_choice')
# 	option = models.CharField(max_length=100,blank=True,default="")
# 	voters = models.ManyToManyField(User,related_name='voters')
#
# 	def __str__(self):
# 		return self.poll.title + self.option

# def user_directory_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'videos/user_{0}/{1}'.format(instance.author.id, filename)

# class VideoPost(Post):
# 	# dog=models.TextField(default="")
# 	video=models.FileField(upload_to=user_directory_path)

Post/forms.py
from django import forms
from .models import GroupPost
from Tag.models import Tag
from django.forms import formset_factory,modelformset_factory
from .models import Poll,PollChoice,Post, VideoPost
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

official_tag=['official','avishkar','freshers']
class PostCreateFrom(forms.ModelForm):
	class Meta:
		model = Post
		fields=['title','tags','content']
		widgets = {
            'content': SummernoteWidget(),
        }
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user',None)
		super().__init__(*args,**kwargs)
		print(user)
		if not user.is_superuser:
			self.fields['tags'].queryset=Tag.objects.exclude(name__in=official_tag)

class PostUpdateFrom(forms.ModelForm):
	class Meta:
		model = Post
		fields=['title','tags','content']
		widgets = {
            'content': SummernoteWidget(),
        }
	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user',None)
		super().__init__(*args,**kwargs)
		print(user)
		if not user.is_superuser:
			self.fields['tags'].queryset=Tag.objects.exclude(name__in=official_tag)

class PollForm(forms.ModelForm):

	class Meta:
		model = Poll
		fields = ['title']

PollChoiceFormset = modelformset_factory(
    PollChoice,
    fields=('option', ),
    extra=4,
    widgets={
        'name': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'enter option'
            }
        )
    }
)

class GroupPostCreateForm(forms.ModelForm):

	class Meta:
		model = GroupPost
		fields = ['title','tags','content']
		widgets = {
            'content': SummernoteWidget(),
        }
	def __init__(self,*args, **kwargs):
		users = kwargs.pop('user',None)
		super().__init__(*args,**kwargs)
		print(users)
		if not users.is_superuser:
			self.fields['tags'].queryset=Tag.objects.exclude(name__in=official_tag)

class SearchForm(forms.Form):

	SearchTerm = forms.CharField(required = True)

class VideoCreateForm(forms.ModelForm):
	class Meta:
		model = VideoPost
		fields = ['title', 'tags', 'content','video']
		widgets = {
			'content': SummernoteWidget(),
		}

	def __init__(self, *args, **kwargs):
		users = kwargs.pop('user', None)
		super().__init__(*args, **kwargs)
		if not users.is_superuser:
			self.fields['tags'].queryset = Tag.objects.exclude(name__in=official_tag)

Post/views.py
import json
from json import loads, load

import rest_framework.generics
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework import generics, permissions
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.generics import ListCreateAPIView
from rest_framework.response import Response

from Post.models import Post, Comment
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from rest_framework import generics, status

from rest_framework.decorators import api_view, authentication_classes, permission_classes

from Post.serializers import PostDetailSerializer

from .models import Post


# class PostListView(ListCreateAPIView):
#     serializer_class =PostDetailSerializer

# queryset = Post.objects.all()
# def get_queryset(self):
# last_two_days = now() - timedelta(days=2)
# return Question.objects.filter(pub_date__gt=last_two_days)
#
# def likeIt(request):
#     if(request.method==request.POST):
#         PO
class PostCreateView(generics.CreateAPIView):
    serializer_class = PostDetailSerializer

    def post(self, request, *args, **kwargs):
        return Response({"hey": "hey"}, status=status.HTTP_200_OK)


class PostDetailView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer

    def get_queryset(self, id):
        return Post.objects.all().filter(id=id)

    def get(self, request, post_id, *args, **kwargs):
        # print(request.bod)
        # data = json.loads(request.body)
        # print(data)
        # post_id = data['post_id']
        query = self.get_queryset(post_id)
        if (len(query) == 0):
            return JsonResponse({'success': False, 'error': 'PostId does not exist'}, status=status.HTTP_404_NOT_FOUND)
        serializer = PostDetailSerializer(query[0], context={'user_who_asked': request.user})
        return Response(serializer.data)

    def post(self, request, *args, **kwargs):
        # return Response({"hey": "hey"}, status=status.HTTP_200_OK)
        # request.data['author']=request.user
        print(request.data)
        data = request.data
        # thePost=self.serializer_class(data=request.data)
        # thePost.is_valid()
        thePost = Post(title=data['title'], content=data['content'], author=request.user, image=data['image'])
        thePost.save()
        return Response({"hey": "success"}, status=status.HTTP_200_OK)
        # x = self.serializer_class(thePost, context={'user_who_asked': request.user})
        # x.is_valid()
        # print(x.data)
        # if():
        #     print("got correct data")
        # thePost.
        # data = json.loads(request.body)
        # post_id=data['post_id']
        # query = self.get_queryset(post_id)
        # if(len(query)==0):
        # return JsonResponse({'success': False, 'error': 'PostId does not exist'}, status=status.HTTP_404_NOT_FOUND)
        # serializer = PostDetailSerializer(query[0],context={'user_who_asked': request.user})
        # return Response(serializer.data)


class PostListView(generics.ListCreateAPIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]
    # authentication_classes = [TokenAuthentication]
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer

    # def get_object(self):
    #     return self.request.user
    def get_queryset(self):
        # _representation(self, instance):
        # x = super().to_representation(instance)
        # user = self.context['user_who_asked']
        # x['is_liked'] = instance.likers.filter(pk=user.pk).exists()
        # x['views'] = len(x['views'])
        # return x
        return Post.objects.all()
        # .filter(author=self.request.user)

    def list(self, request):
        # Note the use of `get_queryset()` instead of `self.queryset`
        queryset = self.get_queryset()
        print("request for post from", request.user)
        serializer = PostDetailSerializer(queryset, many=True, context={'user_who_asked': request.user})
        # serializer = PostDetailSerializer(queryset, many=True)

        # PostDetailSerializer()
        # return JsonResponse(serializer.data)
        # serializer.is_valid()
        return Response(serializer.data)


#  if(request.user.is_authenticated):
#      queryset = self.get_queryset()
#      serializer = PostDetailSerializer(queryset, many=True)
#      return J(serializer.data,status=)
# else:
#  return Response()
@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def post_like(request):
    print("got request for like")
    # data = request.data
    data = json.loads(request.body)
    post_id = int(data['post_id'])
    print("post id recieved ", post_id)
    query = Post.objects.all().filter(pk=post_id)
    if (len(query) > 0):
        post = query.first()
        post.likers.add(request.user)
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)
    return JsonResponse({'success': False, 'error': 'PostId does not exist'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def post_dislike(request):
    print("got request for dislike")
    # print(request.data)
    # data = json.loads(request.body)
    data = json.loads(request.body)
    post_id = int(data['post_id'])
    print("post id recieved ", post_id)
    query = Post.objects.all().filter(pk=post_id)
    if (len(query) > 0):
        post = query.first()
        post.likers.remove(request.user)
        # post.likers.add(request.user)
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)
    return JsonResponse({'success': False, 'error': 'PostId does not exist'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def comment_like(request):
    print("got request for comment like")
    # data = request.data
    data = json.loads(request.body)
    comment_id = int(data['comment_id'])
    print("comment id recieved ", comment_id)
    query = Comment.objects.all().filter(pk=comment_id)
    if (len(query) > 0):
        comment = query.first()
        comment.likers.add(request.user)
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)
    return JsonResponse({'success': False, 'error': 'comment  does not exist'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def comment_dislike(request):
    print("got request for comment like")
    # data = request.data
    data = json.loads(request.body)
    comment_id = int(data['comment_id'])
    print("comment id recieved ", comment_id)
    query = Comment.objects.all().filter(pk=comment_id)
    if (len(query) > 0):
        comment = query.first()
        comment.likers.remove(request.user)
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)
    return JsonResponse({'success': False, 'error': 'comment does not exist'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
# @authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([permissions.IsAuthenticated])
def commentSection(request):
    # data = json.loads(request.body)
    data = request.data
    post_id = data['post_id']
    Comment.objects.all().filter(post=post_id)

class CommentDetailView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    def get_queryset(self, id):
        return Post.objects.all().filter(id=id)
    def post(self, request, *args, **kwargs):
        print(request.data)
        data=request.data
        post_id=int(data['post_id'])
        parent_comment_id = int(data['parent_comment_id'])
        content=str(data['content'])
        post=Post.objects.get(id=post_id)
        print(post)
        parent_comment=None
        if(parent_comment_id !=-1 ):
            parent_comment=Comment.objects.get(id=parent_comment_id)
            new_comment = Comment(content=content, post=post, parent=parent_comment, author=request.user)
        else:
            new_comment=Comment(content=content,post=post,author=request.user)
        new_comment.save()
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)
# @api_view(['GET', ])
# def PostListView(request):
#     # queryset = User.objects.all()
#
#
#
#     # if request.user.is_authenticated:
#     # print(list(request.GET))
#     # request.get('post_from')
#     # requestData = load(request.body)
#     # body_unicode = request.body.decode('utf-8')
#     # body = loads(body_unicode)
#     # requestData = loads(body)
#     # print(requestData)
#     print(request.body)
#     requestData = loads(request.body)
#     # page_number = requestData['page_number']
#     #
#     post_from = 0
#     post_from = requestData['post_from']
#     if (post_from < 0):
#         return JsonResponse({'ERROR': 'post_from is less than 0'}, status=status.HTTP_400_BAD_REQUEST)
#     post_till = 2
#     post_till = requestData['post_till']
#     if (post_till < 0):
#         return JsonResponse({'ERROR': 'post_till is less than 0'}, status=status.HTTP_400_BAD_REQUEST)
#     # page_number = requestData['page_number']
#     # page_number = requestData['page_number']
#     posts = Post.objects.filter().order_by('-date_posted')[
#             max(0, post_from):min(len(Post.objects.all()), max(post_till, 0))]
#     # posts = Post.objects.all()
#     serializer = PostDetailSerializer(posts, many=True)
#     return Response(serializer.data, status=status.HTTP_200_OK)
# paginator= Paginator(posts,10)
# page_number = request.GET.get('page')
# page_obj=paginator.get_page(page_number)

# tags = Tag.objects.all
# groups = Group.objects.all
#
# form1 = SearchForm(request.POST)

Post/templates/Post/about.html
{%  extends "base.html" %}
{% block content %}
<h1> About </h1>
{% endblock content %}

Post/templates/Post/comment.html
{%  extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<p class="text-muted"> <a href="{% url 'post-detail' posty.id%}">Commenting on Post: '{{posty.title}}' by {{posty.author.username}}</a></p>
	<div class="content-section">
		<form method="POST" >
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Comment </legend>
				{{form|crispy}}
			</fieldset>
			<div class="form-group">
			<button class="btn btn-outline-info" type="submit"> Post </button>
			</div>
		</form>
	</div>
{% endblock content %}

Post/templates/Post/home.html
{% extends "base.html" %}
{% load static %}

{% block navBar %}
{% include 'snippets/mainNav.html' %}
{% endblock  %}


{% block content %}
<!-- <div class="container"> -->
{% include 'Post/homePageMembers/homePageParallax.html' %}
<style>
	.thinText {
		font-weight: 160;
	}

	#leftBar {
		height: 98vh;
	}

	#postCalone {
		max-height: 98vh !important;
		overflow-y: scroll;
	}

	@media screen and (max-width: 670px) {
		#postCalone {
			max-height: 98vh !important;
			overflow-y: scroll;
		}
	}
</style>
<div class="row">
	<div id="leftBar" class="blackShade2 col s12 m3 l3" ">
		<!-- Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos nobis aliquam ipsam placeat optio quia consequatur a minima incidunt temporibus voluptates autem repellendus repudiandae, et, earum minus consectetur voluptas animi. -->
		<div class=" row">
		<div class=" col s12 m9 offset-m3  ">

			{% include 'Post/homePageMembers/leftCreateBar.html' %}
		</div>
	</div>
</div>


<div id="postCalone" class="col s12 m6 ">
	<ul class="blackShade2 tabs">
		<li class=" tab col s4">
			<a href="#recentPosts" class="active ">
				Recent Posts
			</a>
		</li>
		<li class="tab col s4">
			<a href="#searchPosts" class="">
				Search Posts
			</a>
		</li>
		<li class="tab col s4">
			<a href="#announcements" class="">
				announcements
			</a>
		</li>
	</ul>

	<div id="recentPosts" class="col s12">
		{% include 'Post/homePageMembers/recentPosts.html' %}
	</div>
	<div id="searchPosts" class="col s12">
		<!-- <h2 class="active indigo-text text-darken-4">Search Posts</h2> -->
		<h2 class="white-text thinText">Search</h2>
		<div id="search">{% include 'Post/searchresults.html' %}</div>
	</div>
	<div id="announcements" class="col s12">
		<h2 class="white-text thinText">Announcements</h2>

		{% include 'Post/homePageMembers/announcements.html' %}
	</div>
</div>
<div class=" col s12 m3 l3">
	{% include 'Post/homePageMembers/rightSideBar.html' %}

	<!-- Modal Structure -->
	<style>
		#modal11 {
			width: 80vw;
			height: 80vh;
			overflow-y: scroll;
		}

		@media screen and (min-width: 600px) {
			#modal11 {
				width: 80vw;
				height: 80vh;
				overflow-y: hidden;
			}
		}
	</style>
	<div id="modal11" class=" modal">
		<div id="modal11content" class="modal-content">
			<h4>Modal Header</h4>
			<p>A bunch of text</p>
		</div>
		<!-- <div class="modal-footer">
			<a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
		</div> -->
	</div>
</div>

<div id="modal1"></div>
{% endblock content %}
{% block js %}
<script type="text/javascript">
	$(document).ready(function (event) {
		// $("bodt").addClass("grey");
		// $('.modal').modal();
		$(document).on("click", "#searchterm", function (event) {
			var searchterm = $("#searchcontent").val();

			$.ajax({
				type: "POST",
				url: '{% url "search" %}',
				data: {
					searchterm: searchterm,
					csrfmiddlewaretoken: "{{csrf_token}}",
				},
				success: function (response) {
					$("#search").html(response["form"]);
					console.log(searchterm);
					// $("#love").addClass("red-text");
				},
				error: function (rs, e) {
					console.log(rs.responseText);
				},
			});
		});
		$(document).on("click", ".postCardOpenModal", function (event) {
			console.log(event.target.id);
			event.preventDefault();
			let id = event.target.id;
			$.ajax({
				type: "GET",
				url: "/post/" + id,
				success: function (response) {

					$('#modal11content').load("/post/" + id + " #modal1",
						function () {});
					$('.modal').modal('open');
					console.log(searchterm);
					// $("#love").addClass("red-text");
				},
				error: function (rs, e) {
					console.log(rs.responseText);
				},
			});
		});
		$(document).on('click', '#like', function (event) {
			event.preventDefault();


			var pk = $(this).attr('value');


			$.ajax({
				type: 'POST',
				url: '{% url "like-post" %}',
				data: {
					'id': pk,
					'csrfmiddlewaretoken': '{{csrf_token}}'
				},
				success: function (response) {
					$('#like-section').html(response['form'])
					console.log('Success');
					// $("#love").addClass("red-text");
				},
				error: function (rs, e) {
					console.log(rs.responseText);
				}
			});

		});

		function create_post(id) {
			console.log("create post is working!") // sanity check
			$.ajax({
				url: "/post/" + id + "/comment/new/", // the endpoint
				type: "POST", // http method
				data: {
					the_content: $('#id_content').val(),
					'csrfmiddlewaretoken': '{{csrf_token}}'
				}, // data sent with the post request

				success: function (json) {

					$('#comment-section').load(
						"/post/" + id + "/" + " #comment-section",
						function () {});

					console.log("success"); // another sanity check
				},

				// handle a non-successful response
				error: function (xhr, errmsg, err) {
					$('#results').html(
						"<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " +
						errmsg +
						" <a href='#' class='close'>&times;</a></div>"
					); // add the error to the dom
					console.log(xhr.status + ": " + xhr
						.responseText
					); // provide a bit more info about the error to the console
				}
			});
		};
		$(document).on('submit', '.post-form', function (event) {

			event.preventDefault();
			console.log("form submitted!"); // sanity check
			let id = event.target.id;
			console.log(id);
			create_post(id);
		});
		// $('#sendButton').on('click', function (event) {
		//     event.preventDefault();
		// 	console.log("form submitted!");// sanity check
		// 	console.log(event.target);
		//     // create_post();
		// });

	});
</script>
{% endblock %}

Post/templates/Post/post_detail.html
{% load mathfilters %}
{% load static %}


<div id="modal1">

    <style media="screen">
        /* .circular--portrait {
  position: relative;
  width: auto;
  height: 40px;
  overflow: hidden;
  border-radius: 50%;
}

.circular--portrait img {
  width: 100%;
  height: auto;
} */
        .circular--square {
            border-radius: 50% !important;
        }

        .circular--landscape {
            margin: 4vh;
            display: inline-block;
            position: relative;
            max-width: 10vh;
            max-height: 10vh;
            /* width: 200px; */
            height: 10vh;
            overflow: hidden;
            border-radius: 50%;
        }

        .circular--landscape img {

            width: auto;
            height: 100%;
            /* margin-left: -50px; */
        }

        #mainContentCard {}

        @media screen and (min-width: 600px) {
            #comment-section {
                /* max-height: fit-content; */
                max-height: 50vh;
                overflow-y: scroll;
            }
        }

        #intro {
            max-height: 30vh;
            width: auto;
            /* margin: auto; */
        }
    </style>
    <div class="conatiner">
        <div class=" row">
            <div class="col s12 m8">
                <div id="mainContentCard" class="card">
                    <div class="card-content">
                        <div class="row">
                            <div class="col s10 l10 ">
                                <h2>{{ object.title }}</h2>

                            </div>

                            <div class="col s1 l1 ">
                                <div class="center-align">
                                    <div id="like-section"> {% include 'Post/like-section.html' %} </div>
                                </div>

                            </div>
                            <div class="col s1 l1 ">
                                <div class="right-align">
                                    {% if object.author == user %}
                                    <span class="card-title activator grey-text text-darken-4"><i
                                            class="material-icons right">more_vert</i></span>
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                        <a class="mr-2" href="{% url 'profile' slug=object.author.username %}">{{ object.author }}</a>
                        <p class="right">{{ object.date_posted }}</p>


                        <p>
                            {% for tag in tags %}
                            <a href="{% url 'explore-tag' tag %}"> #{{tag}} </a>
                            {% endfor %}
                        </p>
                        <p class="article-content">{{ object.content|safe }}</p>
                        <p> Views: {{object.views.count}} </p>
                        {% include "Post/poll_detail.html" %}

                        {% if object.type == 1%}
                        <div class="row">
                            <div class="col s6 offset-s3">
                                <video class="center" id="intro" type="video/mp4" controls preload autoplay>
                                    <source class="center"  src="{{ vpost.video.url }}" type="video/mp4">
                                </video>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="card-reveal">
                        {% if object.author == user %}
                        <span class="card-title grey-text text-darken-4">What to do<i
                                class="material-icons right">close</i></span>

                        <a class="btn btn-large orange waves-effect waves-light red"
                            href="{%url 'post-update' object.id%}">Update </a>
                        <a class="btn btn-large red waves-effect waves-light red"
                            href="{%url 'post-delete' object.id%}">
                            Delete </a>
                       
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="col s12 m4">

                <div id="comment-section">
                    <ul class="collection">
                        {% for comment in comments %}
                        {% include 'Post/homePageMembers/commentCardSmall.html' %}
                        {% endfor %}
                    </ul>

                </div>
                <form class="post-form" id="{{object.id}}">

                    {%csrf_token%}

                    <div class="input-field">
                        <i class="material-icons prefix">message</i>
                        <textarea id="id_content" class="materialize-textarea" cols="20" rows="20"></textarea>
                        <label for="message">Your Message</label>
                    </div>

                    <div class="input-field center">
                        <button id="sendButton" class="btn" type="submit">Submit</button>
                    </div>
                </form>

                <!-- <ul class="collapsible">
                <li>
                    <div class="collapsible-header"><i class="material-icons">filter_drama</i>Continue the Conversation
                    </div>
                    <div class="collapsible-body"> -->


                <!-- </div>
                </li>
            </ul> -->
            </div>
        </div>






    </div>





</div>